apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-api-service
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-web
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 5000 
  type: {{ .Values.web.service.type }}
  