# Deployment do MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: container-mongodb
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongopwd
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongouser

---
# Service do MongoDB
apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
  type: ClusterIP

---
# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: container-app
        image: felippedeiro/rotten-potatoes:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: "admin"
        - name: MONGODB_HOST
          value: service-mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: "mongouser"
        - name: MONGODB_PASSWORD
          value: "mongopwd"

---
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    nodePort: 30000 
    port: 80 
    targetPort: 5000 
  type: NodePort
