# Deployment do MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: container-mongodb
          image: mongo:4.4.6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser

---
# Service do MongoDB
apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  type: ClusterIP

---
# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: container-app
          image: felippedeiro/rotten-potatoes:v1
          ports:
            - containerPort: 5000 # porta que o app pode ser acessado dentro do container
          env:
            - name: MONGODB_DB
              value: "admin"
              # host é o mesmo nome do service
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: "mongouser"
            - name: MONGODB_PASSWORD
              value: "mongopwd"

---
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    app: web
  ports:
    - nodePort: 30000 # 'nodePort' é a porta de entrada para o acesso a aplicacao. o service envia o tráfego recebido em 'nodePort' e encaminha para a porta que o service está escutando, 'port'.
      port: 80 # o service redireciona o tráfego recebido em 'Port' para 'targetPort', que é a porta onde o conteiner expos a aplicacao.
      targetPort: 5000 # porta que os containers irao escutar
  type: LoadBalancer